#!/usr/bin/perl -w

use strict;
use FindBin qw ($Bin);
use lib $Bin;
use AMDRA;

&fixEnv ();

my @cmd = ("$AMDRA_PREFIX/$OMPI_PREFIX/bin/mpif90", 
           "-Qunused-arguments",
           @ARGV, "-L$AMDRA_PREFIX/lib", "-Wl,-rpath,$AMDRA_PREFIX/lib",
           "-L/usr/lib/gcc/x86_64-linux-gnu/13", "-Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/13");

&fixLink (@cmd);

exec (@cmd);

