.TH optionspack 1
.ds )H METEO-FRANCE - CNRM/GMAP
.SH NAME
optionspack \- display the available compilers configurations
.PP
.SH SYNOPSIS
.B optionspack
.PP
.SH DESCRIPTION
.B optionspack
displays the configuration files names available, and for each of them, displays
the equivalent pair of options
.B -l
and
.B -o
used by
.B gmkpack\fR.
.PP
.SH AUTHOR
Ryad El Khatib   <ryad.elkhatib@meteo.fr>
.PP
.SH SEE ALSO
.BR gmkpack(1),
.BR gmkfilemaker(1).
