#!/bin/bash
########################################################################
#
#    Script mkintfb
#    --------------
#
#    Purpose : wrapper of the interfaces generator
#    -------   
#
#    Usage : mkintfb 
#    -----
#              $1 : file list of element to treat
#              $2 : modules list
#              $3 : project
#              $4 : working directory for interfaces generator
#              $5 : list of autogenerated interfaces
#              $6 : working directory for source code pre-processing
#
#    Environment variables :
#    ---------------------
#
########################################################################

export LC_ALL=C

export INTFBLIST=$3
export LOC_INTFBDIR=$4

project=$3


if [ $GMK_CPP_INTFB -eq 0 ] ; then

  export MKMAIN_INPUT=$MKMAIN
  $GMKROOT/intfb/$project/mkintfb.pl $1 $2 $5

else

# Experimental option to pre-process a .F90 source file before making its auto-generated interface.

  CPPTMPDIR=$6
# Define preprocessor and its intrinsic options :
# -traditional-cpp does help by preserving at least a double slash before a continuing line.
# "-x c" options should not be of much help.
  if [ "$CPP" ] ; then
    CPP_COMMAND="$CPP -w -P -traditional-cpp"
  else
#   CPP is not defined, use the compiler instead :
    CPP_COMMAND="$VCCNAME -E -w -P -traditional-cpp"
  fi

  if [ $(grep -c "^${project}/" $1) -ne 0 ] ; then
    echo "Preprocessing ..."
    mkdir -p $CPPTMPDIR
    VOBNAME=$(echo $project | tr '[a-z]' '[A-Z]')
    OPTVOB=GMK_FCFLAGS_${VOBNAME}
#   Preprocess each file, removing first any #include directive, problematic and useless for interfaces generation  :
#   The removal of "#include " directives is necessary otherwise cpp would not work
#   (because of risk of recursivity with included autogenerated interfaces not yet generated)
#   Keeping #include directive should be possible, but it requires to make the auto-generated interfaces twice,
#   the first time without pre-processing.
    for file in $(grep "^${project}/" $1) ; do
      tmpfile=$CPPTMPDIR/$file
      mkdir -p $(dirname $tmpfile)
      CplOpts="$CPP_COMMAND $MACROS_FRT $(env | grep "^${OPTVOB}=" | cut -d"=" -f2-) -"
#      echo "grep -v \"\#include \" $file | ${CplOpts}"
      eval grep -v "\#include " $MKMAIN/$file | $CplOpts > $tmpfile
      if [ ! -f $tmpfile ] ; then
        echo "Failed to pre-process $file - use the non-pre-processed one"
        \ln -s $MKMAIN/$file $tmpfile
      fi
    done
#    find $CPPTMPDIR -name "*" -type f -print | xargs ls -l
    echo "... Done."
  fi

  export GMKBUILD=$CPPTMPDIR
  $GMKROOT/intfb/$project/mkintfb.pl $1 $2 $5
  /bin/rm -rf $CPPTMPDIR

fi
