#!/bin/bash
########################################################################
#
#    Script Pmkintfb
#    --------------
#
#    Purpose : In the framework of a pack : distribute generation of interfaces
#    -------   
#
#    Usage : Pmkintfb $1
#    -----
#              $1 : file list of element to treat
#              $2 : modules list
#              $3 : list of autogenerated interfaces
#              $4 : project
#              $5 : working directory for interface generator
#              $6 : working directory for source code pre-processing
#
#    Environment variables :
#    ---------------------
#            GMK_THREADS : number threads
#            GMKWRKDIR   : main working directory
#            GMKROOT     : gmkpack root directory
#
########################################################################

export LC_ALL=C
if [ "$ZSH_NAME" = "zsh" ] ; then
  setopt +o nomatch
fi

rc=0

if [ -s $1 ] ; then

  export GMK_CPP_INTFB=${GMK_CPP_INTFB:=0}
# the existence of a file .cpp_intfb will mark the use of cpp before making the autogenerated interfaces :
  NVIEW=$(echo $GMKVIEW | tr " " "\n" | wc -l)
  if [ $NVIEW -gt 1 ] || [ -d $MKMAIN/$GMKINTFB ] ; then
# user packs use the value of the main pack ; already-compiled main packs as well ; unless forced by option 2 :
    CPP_INTFB_CONTROL_FILE=$(find $(dirname $(ls -l $MKTOP/$GMKMAIN | $AWK '{print $NF}')) -name ".cpp_intfb" -type f)
    if [ "$CPP_INTFB_CONTROL_FILE" ] ; then
      export GMK_CPP_INTFB=1
    elif [ $GMK_CPP_INTFB -eq 1 ] ; then
      export GMK_CPP_INTFB=0
    fi  
  else
# brand new or cleaned main pack :
    if [ $GMK_CPP_INTFB -ne 0 ] ; then
      touch $MKTOP/.cpp_intfb 
    fi
  fi
  if [ $GMK_CPP_INTFB -ne 0 ] ; then
    project=$4
    if [ $(grep -c "^${project}/" $1) -ne 0 ] ; then
      echo
      echo "***************************************************************************"
      echo "* EXPERIMENTAL : GENERATION OF INTERFACES FROM PARTLY PRE-PROCESSED FILES *"
      echo "***************************************************************************"
      echo
    fi
  fi

  OUTLIST=$3
  WORKDIR=$5
  CPPTMPDIR=$6
  export MPSH_DRV_INPUT_ARGUMENTS=3
  $GMKROOT/aux/mpsh_driver.sh $GMKROOT/aux/mkintfb.sh $1 $2 $4 $WORKDIR $OUTLIST $CPPTMPDIR
  rc=$?
  if [ $(find $(dirname $OUTLIST) -name "$(basename $OUTLIST).*" -type f -print | wc -l) -ne 0 ] ; then
    cat ${OUTLIST}.* > $3
    /bin/rm ${OUTLIST}.*
  fi
  /bin/rm -rf ${WORKDIR}.* ${CPPTMPDIR}.*

fi

exit $rc
