#!/bin/bash

set -x
set -e

export GPUPACK_PREFIX=$HOME/gpupack

cd $GPUPACK_PREFIX

# Load gpupack shell functions

. $GPUPACK_PREFIX/scripts/gpupack

# Create gpupack profile

create_gpupack_sh

# Load gpupack profile

. ./gpupack.sh

# Install common libraries (architecture independent)

# common_install

# Choose a compiler

ARCH=NVHPC2307

# Install architecture dependent libraries

# libraries_install  

# Pick a cycle & a branch

CYCLE=49t0
BRANCH=rapsgpu+openacc+pb11
REPO=https://github.com/pmarguinaud/IAL.git

# Choose architecture flavor

OPT=1d

# Create a pack

pack_create 

# Compile the pack

pack_compile

