#!/bin/bash

set -x
set -e

export GPUPACK_PREFIX=$HOME/gpupack

cd $GPUPACK_PREFIX

. $GPUPACK/scripts/gpupack

create_gpupack_sh

. ./gpupack.sh

: common_install

#for ARCH in NVHPC2303 INTEL1805
for ARCH in NVHPC2305 
do
: libraries_install  
done


CYCLE=49t0
BRANCH=compile_with_pgi_2303-field_api
REPO=https://github.com/pmarguinaud/IAL.git

if [ 0 -eq 1 ]
then
for ARCH in NVHPC2305
do
  for OPT in 1d
  do
    pack_create 
exit
  done
done
fi



for ARCH in NVHPC2305
do
  for OPT in 1d
  do
    pack_compile
  done
done

