#!/usr/bin/perl -w

use strict;
use FindBin qw ($Bin);
use lib $Bin;
use NVHPC;

&fixEnv ();

my @cmd = ("$NVHPC_ROOT/$OMPI_PREFIX/bin/mpif90", @ARGV, 
           "-L$NVHPC_ROOT/compilers/lib", "-Wl,-rpath,$NVHPC_ROOT/compilers/lib", '-lnvhpcatm',
           "-L$NVHPC_ROOT/$CUDA_PREFIX/targets/x86_64-linux/lib", "-Wl,-rpath,$NVHPC_ROOT/$CUDA_PREFIX/targets/x86_64-linux/lib", '-lnvhpcwrapnvtx', '-lnvToolsExt',
           "-L$NVHPC_ROOT/$OMPI_PREFIX/lib", "-Wl,-rpath,$NVHPC_ROOT/$OMPI_PREFIX/lib", '-lopen-rte', '-lopen-pal');

&fixLink (@cmd);

exec (@cmd);

