#!/bin/bash

prefix=/home/gmap/mrpm/marguina/install/gnu/12.3.0

module () 
{ 
    eval `/usr/bin/modulecmd bash $*`
}

module purge 2>/dev/null
module load intelmpi/2018.5.274 2>/dev/null
export PATH=$prefix/bin:$PATH

exec mpigcc $* -mt_mpi -Wl,-rpath,$prefix/lib64 -lm
