#!/bin/bash

prefix=$(dirname $0)
. $prefix/prolog.sh

# Intel fortran compiler

export TMP=/tmp
# Command
export __INTEL_POST_FFLAGS="$*"
exec ifort -qmkl=sequential -lirc $(echo $LD_LIBRARY_PATH | sed -e "s/:/ -Wl,-rpath,/g" -e "s/^/-Wl,-rpath,/")
