#!/bin/bash

prefix=$(dirname $0)
. $prefix/prolog.sh

# IntelMPI x Intel C       compiler

export TMP=/tmp
# Command
exec mpiicc $* -qmkl=sequential -mt_mpi -lirc $(echo $LD_LIBRARY_PATH | sed -e "s/:/ -Wl,-rpath,/g" -e "s/^/-Wl,-rpath,/")
