#!/bin/bash

prefix=$(dirname $0)
. $prefix/prolog.sh

# IntelMPI x Intel fortran compiler

export TMP=/tmp
export __INTEL_POST_FFLAGS="$*"
exec mpiifort -qmkl=sequential -mt_mpi -lirc $(echo $LD_LIBRARY_PATH | sed -e "s/:/ -Wl,-rpath,/g" -e "s/^/-Wl,-rpath,/")
