#!/bin/bash

# A wrapper for gfortran (+mpi) in the case the compilation would failed because of
# insufficient memory space. The wrapper attempt to recompile with less (if not without) debug information.

mpifort $*
rc=$?
if [ $rc -ne 0 ] ; then
# Compilation failed, try again with less debug info :
  gfortran $(echo "$*" | sed 's/ -g / -g1 /') 2>/dev/null
  rc=$?
else
# Compilation successful
  exit $rc
fi
if [ $rc -ne 0 ] ; then
# Compilation failed again, try again without debug info :
  gfortran $(echo "$*" | sed -e 's/ -g / -g0 /' -e 's/ -g1 / -g0 /') 2>/dev/null
  rc=$?
else
  echo "Compilation failed, workaround successfull with -g1"
  exit $rc
fi
if [ $rc -eq 0 ] ; then
  echo "Compilation failed, workaround successfull with -g0"
  exit $rc
fi
exit $rc
