#!/bin/ksh

# Wrapper for IBM xlf compiler : treat omp business (by Denis Paradis)
# Modified for gmkpack (Ryad El Khatib)
# Should be useless now, according to ECMWF (21/06/2006) R. El Khatib
# No, still useful for ECMWF. Update with HOT.(31/01/2008 R. El Khatib)
# Remove now omp filter (03/09/2010 R. El Khatib)
command="$*"
last=$#
shift $last-1
file="$@"
comp=
comp="-qsmp=omp"
grep -q '\@PROCESS NOOPTIMIZE' $file
if [ $? -eq 0 ] ; then
  comp="-qsmp=omp:noopt"
else
# because lines might be very long with gmkpack (-I...) :
  optimize=
  for string in $command ; do
    if [ "$optimize" != "yes" ] ; then
      echo "$string" | grep -q '^\-O'
      if [ $? -eq 0 ] ; then
        optimize=yes
      fi
    fi
  done
  if [ "$optimize" != "yes" ] ; then
    comp="-qsmp=omp:noopt"
  fi
fi

comp1=
grep -q '^\@PROCESS HOT' $file
if [ $? -eq  0 ] ; then
 comp1="-O4"
fi
echo "mpxlf95_r $comp $comp1"
mpxlf95_r $comp $comp1 $command 2>&1 | grep -v "=== End of Compilation" | grep -v "Compilation successful for file"
exit $?
