#!/bin/bash

module () 
{ 
    eval `/usr/bin/modulecmd bash $*`
}

module purge 2>/dev/null
module load intel/2018.5.274_mkl_nightly_2019u2 2>/dev/null
module load gcc/5.3.0 2>/dev/null

# Intel C       compiler

export TMP=/tmp
# Command
icc $* -mkl=sequential -lirc $(echo $LD_LIBRARY_PATH | sed -e "s/:/ -Wl,-rpath,/g" -e "s/^/-Wl,-rpath,/")
