#!/bin/bash

function create_gpupack_sh ()
{
  set -e

  cat -> $GPUPACK_PREFIX/gpupack.sh << EOF
export GPUPACK_PREFIX=$GPUPACK_PREFIX
export PATH=\$GPUPACK_PREFIX/install/common/fypp/bin:\$GPUPACK_PREFIX/install/common/perl/bin:\$GPUPACK_PREFIX/install/common/cmake/bin:\$GPUPACK_PREFIX/vimpack:\$GPUPACK_PREFIX/gmkpack/util:\$PATH
export ROOTPACK=\$GPUPACK_PREFIX/pack
export HOMEPACK=\$GPUPACK_PREFIX/pack
export GMK_SUPPORT=\$GPUPACK_PREFIX/support

EOF

}

function run_gpupack ()
{
  set -e

# Load gpupack shell functions

  source $GPUPACK_PREFIX/scripts/gpupack

# Create gpupack profile

  create_gpupack_sh

# Load gpupack profile

  source ./gpupack.sh

# Install common libraries (architecture independent)

  if [ ! -d "$GPUPACK_PREFIX/install/common" ]
  then
    common_install
  fi

# Check versions of Perl & cmake

  common_check_versions

# Install architecture dependent libraries

  if [ ! -d "$GPUPACK_PREFIX/install/$ARCH" ]
  then
    libraries_install  
  fi

# Create a pack

  pack_create 

# Compile the pack

  if [ "$COMPILE" == "ON" ]
  then
    pack_compile
  fi
}

source "$GPUPACK_PREFIX/scripts/gpupack.pack"
source "$GPUPACK_PREFIX/scripts/gpupack.common"
source "$GPUPACK_PREFIX/scripts/gpupack.libraries"
  
