#!/bin/bash

declare -F | sort > /tmp/$USER.func.1

function create_gpupack_sh ()
{

  cat -> $GPUPACK_PREFIX/gpupack.sh << EOF
export GPUPACK_PREFIX=$GPUPACK_PREFIX
export PATH=\$GPUPACK_PREFIX/install/common/fypp/bin:\$GPUPACK_PREFIX/install/common/perl/bin:\$GPUPACK_PREFIX/install/common/cmake/bin:\$GPUPACK_PREFIX/vimpack:\$GPUPACK_PREFIX/gmkpack/util:\$PATH
export ROOTPACK=\$GPUPACK_PREFIX/pack
export HOMEPACK=\$GPUPACK_PREFIX/pack
export GMK_SUPPORT=\$GPUPACK_PREFIX/support

export CUDA_CC=$CUDA_CC

EOF

bash $GPUPACK_PREFIX/support/wrap/$ARCH/env.sh >> $GPUPACK_PREFIX/gpupack.sh

}

source "$GPUPACK_PREFIX/scripts/gpupack.pack"
source "$GPUPACK_PREFIX/scripts/gpupack.common"
source "$GPUPACK_PREFIX/scripts/gpupack.libraries"
  
declare -F | sort > /tmp/$USER.func.2

comm -3 /tmp/$USER.func.1 /tmp/$USER.func.2

