#!/bin/bash
########################################################################
#
#    Script intfb_pathpack
#    --------------
#
#    Purpose : In the framework of a pack : to find path for 
#    -------   Include/Modules from autogenerated interfaces
#
#    Usage : intfb_pathpack $1 $2
#    -----
#              $1 : files list (input)
#              $2 : modules list (input)
#
#    Environment variables :
#    ---------------------
#            MKTOP     : directory of all source files
#            MODINC    : prefix for include directory in compiler synthax
#            AWK       : awk program
#            GMKROOT   : gmkpack root directory
#            GMKINTFB  
#            GMKSYS
#
########################################################################
#

export LC_ALL=C

MyTmp=$GMKWRKDIR/intfb_pathpack
mkdir -p $MyTmp
find $MyTmp -name "*" -type f | xargs /bin/rm -f
cd $MyTmp

# Prepare local-modset directories to receive links to modules/headers:

# Modules:
touch modpath
if [ -s $2 ] ; then
  for vob in $(cat $2 | cut -d "/" -f1 | sort -u) ; do
    mkdir -p $MKMAIN/.include/$vob/modules
    echo ${MODINC}${MKMAIN}/.include/$vob/modules >> modpath
  done
fi

# Headers:
touch incpath
# Search everywhere and link to a single directory per project :
# only autogenerated interfaces :
for vob in $(grep "^${GMKINTFB}" $1 | cut -d "/" -f2 | sort -u) ; do
  mkdir -p $MKMAIN/${GMKINTFB}/$vob
  echo ${MODINC}${MKMAIN}/${GMKINTFB}/$vob >> incpath
done

cat incpath modpath > new_incpath
if [ -s new_incpath ] ; then
  if [ $ICS_ECHO -gt 1 ] ; then
    echo Include path :
    cat new_incpath
  fi
  cat incpath >> $MKTOP/.incpath.local
  cat modpath >> $MKTOP/.modpath.local
fi

cd $GMKWRKDIR
\rm -rf intfb_pathpack
