#!/usr/bin/perl -w

use strict;
use FileHandle;
use File::Basename;
use FindBin qw ($Bin);

my @u = qw (CC CXX F77 F90 FC I_MPI_CC I_MPI_CXX I_MPI_F90 I_MPI_FC OMPI_CC OMPI_CXX OMPI_FC);
delete $ENV{$_} for (@u);

sub prefix
{
  use Sys::Hostname;
  my $host  = &hostname ();
  return '/ec/res4/hpcperm/sor/install' if ($host =~ m/^ac\d+-\d+\.bullx$/o);
  return '/opt/softs' if ($host =~ m/^(?:belenos|taranis)/o);
  die ("Unexpected host : $host");
}

sub meteofrance
{
  use Sys::Hostname;
  my $host  = &hostname ();
  return 1 if ($host =~ m/^(?:belenos|taranis)/o);
}

my $NVHPC_PREFIX = &prefix () . '/gcc/9.2.0/hpc_sdk/Linux_x86_64/24.1';
my $OMPI_PREFIX = "comm_libs/12.3/hpcx/hpcx-2.17.1/ompi";
my $CUDA_PREFIX= "cuda/12.3";

local $ENV{LD_LIBRARY_PATH} = "$NVHPC_PREFIX/comm_libs/nvshmem/lib:$NVHPC_PREFIX/comm_libs/nccl/lib:$NVHPC_PREFIX/$OMPI_PREFIX/lib:$NVHPC_PREFIX/math_libs/lib64:$NVHPC_PREFIX/compilers/lib:$NVHPC_PREFIX/cuda/lib64";
local $ENV{PATH} = "$NVHPC_PREFIX/compilers/bin:$ENV{PATH}";
local $ENV{NVHPC_CUDA_HOME} = "$NVHPC_PREFIX/$CUDA_PREFIX";

if ((grep { $_ eq '-E' } @ARGV) && (grep { $_ eq '-P' } @ARGV))
  {
    exec ("/usr/bin/cpp", @ARGV);
  }

my @cmd =
       ("$NVHPC_PREFIX/$OMPI_PREFIX/bin/mpicc", @ARGV, 
      "-L$NVHPC_PREFIX/compilers/lib", "-Wl,-rpath,$NVHPC_PREFIX/compilers/lib", '-lnvhpcatm',
      "-L$NVHPC_PREFIX/$CUDA_PREFIX/targets/x86_64-linux/lib", "-Wl,-rpath,$NVHPC_PREFIX/$CUDA_PREFIX/targets/x86_64-linux/lib", '-lnvhpcwrapnvtx', '-lnvToolsExt', '-lnvf',
      "-L$NVHPC_PREFIX/$OMPI_PREFIX/lib", "-Wl,-rpath,$NVHPC_PREFIX/$OMPI_PREFIX/lib", '-lopen-rte', '-lopen-pal');

if (&meteofrance ())
  {
	  push @cmd,"-Wl,-rpath,/opt/softs/gcc/9.2.0/lib64";
  }


exec (@cmd);
