#!/usr/bin/perl -w

use strict;

my $NVHPC_PREFIX = "/opt/softs/nvidia/hpc_sdk/Linux_x86_64/23.3";
my $CUDA_PREFIX= "cuda/11.8";

local $ENV{LD_LIBRARY_PATH} = "$NVHPC_PREFIX/comm_libs/nvshmem/lib:$NVHPC_PREFIX/comm_libs/nccl/lib:$NVHPC_PREFIX/math_libs/lib64:$NVHPC_PREFIX/compilers/lib:$NVHPC_PREFIX/cuda/lib64";
local $ENV{PATH} = "$NVHPC_PREFIX/compilers/bin:$ENV{PATH}";
local $ENV{NVHPC_CUDA_HOME} = "$NVHPC_PREFIX/$CUDA_PREFIX";

exec ("$NVHPC_PREFIX/compilers/bin/pgc++", @ARGV, 
      "-L$NVHPC_PREFIX/compilers/lib", '-lnvf', '-lnvhpcatm', "-Wl,-rpath,$NVHPC_PREFIX/compilers/lib", 
      "-L$NVHPC_PREFIX/$CUDA_PREFIX/targets/x86_64-linux/lib", "-Wl,-rpath,$NVHPC_PREFIX/$CUDA_PREFIX/targets/x86_64-linux/lib", '-lnvhpcwrapnvtx', '-lnvToolsExt');
